export const walletActionTypes = {
  FETCH_CURRENCIES_REQUEST: 'wallet/FETCH_CURRENCIES_REQUEST',
  FETCH_CURRENCIES_SUCCESS: 'wallet/FETCH_CURRENCIES_SUCCESS',
  FETCH_CURRENCIES_FAILURE: 'wallet/FETCH_CURRENCIES_FAILURE',
};
