export const walletActionTypes = {
  FETCH_CURRENCIES_REQUEST: 'wallet/FETCH_CURRENCIES_REQUEST',
  FETCH_ONLY_CURRENCIES_REQUEST: 'wallet/FETCH_ONLY_CURRENCIES_REQUEST',
  ADD_EXPENSE: 'wallet/ADD_EXPENSE',
  REMOVE_EXPENSE: 'wallet/REMOVE_EXPENSE',
  EDIT_EXPENSE: 'wallet/EDIT_EXPENSE',
  FETCH_EXCHANGE_CURRENCIES: 'wallet/FETCH_EXCHANGE_CURRENCIES',
};
