export const walletActionTypes = {
  FETCH_CURRENCIES_REQUEST: 'wallet/FETCH_CURRENCIES_REQUEST',
  FETCH_CURRENCIES_SUCCESS: 'wallet/FETCH_CURRENCIES_SUCCESS',
  FETCH_CURRENCIES_FAILURE: 'wallet/FETCH_CURRENCIES_FAILURE',
  ADD_EXPENSE: 'wallet/ADD_EXPENSE',
  REMOVE_EXPENSE: 'wallet/REMOVE_EXPENSE',
  EDIT_EXPENSE: 'wallet/EDIT_EXPENSE',
  FETCH_EXCHANGE_RATES_SUCCESS: 'wallet/FETCH_EXCHANGE_RATES_SUCCESS',
  FETCH_EXCHANGE_RATES_FAILURE: 'wallet/FETCH_EXCHANGE_RATES_FAILURE',
};
